### ISSUE TITLE
rerun tests on each save

### ISSUE THREAD

**Issue by kootenpv** [ionrock/pytest-el#3]
I'm wondering if it makes sense to add a hook to saving a file, resulting in running tests?

**Comment by ionrock** [comment]
@kootenpv I think this would be something a user can implement themselves by adding a hook when a buffer is saved rather than including it in pytest.el. 

Thanks for the suggestion!

**Comment by ghost** [comment]
You do not need a hook. The official pytest addon [xdist](https://pytest.org/latest/xdist.html) (`pip install pytest-xdist`) can watch a folder for you, rerunning the tests on each change in the watched folder or any of its subdirectories.

To use it, just open a `bash shell` in emacs (or elsewhere) and run your tests from the project root folder with the `-f` flag. This opens an eternal pytest session that reruns on each save. You might want to crop the test runner buffer since it will grow crazy quickly if you save often.

I find this so useful that I have an external monitor dedicated to it; the upper half contains the unit tests, the lower half of the display contains the integration tests.

From the official description:

`Looponfail: run your tests repeatedly in a subprocess. After each run, pytest waits until a file in your project changes and then re-runs the previously failing tests. This is repeated until all tests pass. At this point a full run is again performed.`

**Comment by ghost** [comment]
What about changing the title to make it more google/discover-able, something like `rerun tests on each save?`.

**Comment by kootenpv** [comment]
Both the title change and the testing method are great suggestions, thanks!

**Comment by ghost** [comment]
Yeah, it is likely to be much more robust to use that method instead of a emacs hook. 

Also note the `-n` (afaicr) parameter in xdist for the number of processors to be used (might slow down your testing if you do not have many/long-running tests though).

**Comment by ionrock** [comment]
@endrebak Thanks for the suggestion! I completely forgot using the xdist plugin, even though that was on by default when I originally started using pytest.el!

You can set the flags you want to use with pytest.el by setting the `pytest-cmd-flags` variable. If you don't want to change it globally, just use a dir-local variable in project. HTH

**Comment by ghost** [comment]
Neat, perhaps a small docupdate would be in order? (I can't really do it since I don't really use `pytest.el`, it is just a part of the python layer in spacemacs so I have it by default).

**Comment by ghost** [comment]
Started using `pytest.el` now, this is my hook (add to `.spacemacs/config` or `.emacs`, whichever applies):

``` elisp
(defun run-pytest-on-save ()
    (if (eq major-mode 'python-mode)
        (pytest-module)))

(add-hook 'after-save-hook 'run-pytest-on-save)
```

You might want to use `pytest-all` instead of `pytest-module` in the snippet above. I use the latter, since I prefer keeping tests/code in the same file (which seems to become more common now in modern langs like `nim` and `rust`). Note that this will run pytest, whether you have tests for your project or not (why wouldn't you?).
