### ISSUE TITLE
support running parametrized test

### ISSUE THREAD

**Issue by parkouss** [ionrock/pytest-el#7]
First, thanks a lot for pytest-el!

Well I love the ability to run one test, using "C-c .". This does not work with parametrized test though - not sure what can be done about it, but I report the issue so we can figure something eventually.

**Comment by ionrock** [comment]
@parkouss I've found the same to be true and after looking into fixing it, I'm imagining it might be tricky. The essential problem is that when you parameterize the test, py.test will create a new name for the function. By default the name is generated by py.test, in which case we'd have to collect the tests first, then try to figure out what tests we should be using. Another wrinkle is that you can also define parameters via the class with the params attribute. I haven't looked into this too closely, but if it renames the classes then that seems to add quite a bit of complexity as well. 

One idea is to punt! If we see a parameterized test method, we could call the parent. So, it would move up to calling the class. That also seems like it could be rather confusing b/c if you had a suite of parameterized tests in a class and you wanted to iterate on one, you'd be out of luck. 

Another idea, and I'm just thinking aloud here, would be to have a py.test UI that collects all the tests and lets you choose. This would be something like a table view that collects the tests and give you a table view you could navigate to. Another UI option would be a helm view. 

Honestly, of the options, the helm view seems the most doable to me, but I doubt I'd want to force a dependency on helm as it is somewhat polarizing. I would be willing to create a pytest-collect function that returns some elisp that could work with helm, at which point someone else (or myself if I'm using helm that week ;) ) could write a pytest-helm plugin. 

Anyway, let me know your interest and I can see if there is a little time to make something happen. Otherwise, I'm leaning towards closing this as WONTFIX. 

Apologies as well for not pointing out this detail. I've run into it as well and just worked around it without thinking I should document the behavior. I'll try to update the README, which I'm sure is severely lacking.

**Comment by parkouss** [comment]
@ionrock thanks for looking at this!
Well yeah I agree to not require the helm dependency - though the idea of having a list of test that can be triggered sounds nice.
Running parametrized tests on their own would just be a nice to have, I don't mind running all the test in that particular case - and obviously there is no easy solution, so WONTFIX seems good to me here with a mention in the README.
Again, thanks for your answer and thoughts.
